== Latex2Asciidoctor

This is the beginning of a project to write
a LaTeX to Asciidoctor-latex converter.
For the moment I am roughing out
a recursive descent parser for
a coarse-grained version of LaTeX. For
tests, (concept and progress), see item
three in the section <<Testing>>.

*Note.* Parser now passes the "identity
test" for a small number of files,
e.g., `empty.tex`, 'paragraphs.tex',
`comment.tex`, `macro.tex`, `inline_math.tex`,
and `display_math.tex`



.Major Todos
* Create tree instead of list  of nodes
  with nodes stored in content field

* Get recursive


== Design notes

We should mimic the structure of Asciidoctor -- in particular, have
abstract and concrete
blocks, where the head and body are blocks, environments are blocks nested
within them, and which can in turn contain other blocks.  The grammar
and parser will have to be reworked for this.


=== The Basic Idea

Latex2Asciidoctor, which is in version the 0.0001,
has the following parts:

* *Reader* takes a string, e.g., a file's contents as input,
then provide text in chunks to a caller via the methods `get_word` and `get_line`.
The instance varables `@current_word` and `@current_line`
point to the last-gotten line and word.  The relationship
_@current_word is in @curent_line_ is preserved regardless
of which the `get` methods is called.

* *Parser* also takes a string as input.  It initializes
a `Reader` object and calls it indirectly via `get_token`.
Set up a Parser with `parser = Parser.new(text)`. The call
`parser.parse` is intended to push an AST onto `parser.stack`.
At the moment what is pushed is a bunch of nodes for elements
of the grammar listed below.  I've tested real AST production
with the same technology and
a simple grammar of arithmetic expressions, one that
recognizes and evaluates things like
`( 1 + 2 ) * ( 3 + 4 )`.  The correct AST is built by
a recursive descent parser constructed by hand from the grammar.
The nodes of the AST are instances of `Tree::TreeNode` (see
https://github.com/evolve75/RubyTree ).
We use `Tree::TreeNode` this projecct as well,
though the grammar at he moment is very simple.


* *Other files* in `lib/` are mosty junk and/or irrelevant
 will be removed.


=== Grammar

----
  # Grammar
  # -------

  # Productions
  # -----------
  # document = header BEGIN_DOC body END_DOC
  # body = { expr }
  # expr = { text | macro | environment | inline_math | display_math }
  # macro = \command \{ {args} \}
  # environment = BEGIN_ENV expr END_ENV
  # inline_math = $ math_text $
  # display_math = \[ math_text \]

  # Terminals:
  # ----------
  # BEGIN_DOC = '\begin{document}'
  # END_DOC = '\end{document}'

  # Pseudoterminals
  # --------------
  # BEGIN_ENV = '\begin{' env_name '}'
  # END_ENV = '\end{' env_name '}'
----

A pseudoterminal such as `\begin{theorem}`
matches `\end{theorem}`, `\begin{definition}`
matches `\end{definition}`, etc.

WARNING: the production for `environment` is not yet implemented per
the grammar.

==== Testing

Still very primitive, but I am using rspec and want
to use @jirutka's doctest as well.  The Reader is well
tested.

To test the parser, run
```
  $ rspec spec/parser_spec.rb
```
At the moment I am working on

. making the parser produce
a tree instead of a list of nodes.

. the method `Parser # render_tree` in module `Display`

. passing the "identity test"
in `parser_spec.rb`:  the yield of the parser
should be the same as the input text modulo white space.
Once the parser implements whatever the final grammar
is and passes this text, another render method
can be developed to produce the proper Asciidoctor text.
